name: Make Package Public
on: workflow_dispatch
permissions:
  packages: write
jobs:
  make-public:
    runs-on: ubuntu-latest
    steps:
      - name: Make package public
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X PATCH \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/user/packages/container/tgnd-flux-lora" \
            -d '{"visibility":"public"}'
